# Utiliser une image officielle Go pour le développement
FROM golang:1.24

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier go.mod et go.sum pour gérer les dépendances (permet le cache)
COPY go.mod go.sum ./

# Télécharger les dépendances Go
RUN go mod download

# Copier tout le code source dans le conteneur
COPY . .

# Exposer le port que l'application va écouter
EXPOSE 8080

# Lancer l'application avec go run, directement dans le conteneur
CMD ["/bin/bash"]
# CMD ["go", "run", "cmd/main.go"]